### ISSUE TITLE
Refactor GetBalances API and Ticker struct

### ISSUE THREAD

**Issue by fiore** [saniales/go-hitbtc#5]
Refactor `GetBalance()` and `GetBalances()` removing duplicated code.
Refactor ticker `UnmarshalJSON` avoiding error due empty value.
Refactor tickers `UnmarshalJSON` removing Zero Volume rows.

**Comment by saniales** [comment]
I add a note that this would also remove the unexisting `payment/balance` endpoint, which was in bitbandi's version and it's not available anymore, due to v2 upgrade.
